import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { User, Stethoscope as StethoscopeIcon, FileText, CalendarClock, FlaskConical } from "lucide-react";
import { Input } from "@/ui/Input.jsx";
import { Textarea } from "@/ui/Textarea.jsx";
import { Progress } from "@/ui/Progress.jsx";
import { Button } from "@/ui/Button.jsx";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { useToast } from "@/context/toast.jsx";
import { runAIDiagnosis } from "@/lib/aiDiagnosis.js";
import {
  registerPatient,
  createEncounter,
  createAppointment,
  createLabOrder,
  createEmergencyAlert,
  uploadEncounterFiles,
} from "@/lib/hospitalApi.js";

const DOCTOR_MAP = {
  ENT:              ["Dr. Mehra (ENT)", "Dr. Iyer (ENT)"],
  Cardiology:       ["Dr. Rao (Cardio)", "Dr. Malik (Cardio)"],
  Dermatology:      ["Dr. Kapoor (Derm)", "Dr. Sen (Derm)"],
  "General Medicine": ["Dr. Nair (Medicine)", "Dr. Das (Medicine)"],
  Pediatrics:       ["Dr. Verma (Pediatrics)", "Dr. Singh (Pediatrics)"],
  Gynecology:       ["Dr. Patel (Gynecology)", "Dr. Banerjee (Gynecology)"],
  Orthopedics:      ["Dr. Thomas (Ortho)", "Dr. Kulkarni (Ortho)"],
};

const STEPS = [
  { label: "Details",     description: "Patient registration",    Icon: User },
  { label: "Dept",        description: "Choose department",       Icon: StethoscopeIcon },
  { label: "Symptoms",    description: "Symptoms & uploads",      Icon: FileText },
  { label: "Diagnosis",   description: "AI diagnosis & plan",     Icon: FlaskConical },
  { label: "Appointment", description: "Schedule appointment",    Icon: CalendarClock },
];

const initialForm = {
  name: "", age: "", gender: "", phone: "", email: "", address: "", emergencyContact: "",
  department: "", symptoms: "", files: [], duration: "", severity: 5,
  history: "", allergies: "", appointmentDate: "", appointmentTime: "", doctor: "",
};

export default function PatientPortal({ accentColor, roleIcon: RoleIcon }) {
  const navigate = useNavigate();
  const { addToast } = useToast();
  const [step, setStep]         = useState(0);
  const [form, setForm]         = useState(initialForm);
  const [aiResult, setAiResult] = useState(null);
  const [loading, setLoading]   = useState(false);
  const [patientId, setPatientId]     = useState(null);
  const [encounterId, setEncounterId] = useState(null);

  const upd = (patch) => setForm((f) => ({ ...f, ...patch }));

  const validate = () => {
    const container = document.querySelector(`[data-step="${step}"]`);
    if (!container) return true;
    for (const f of container.querySelectorAll("input,select,textarea")) {
      if (f.required && !f.checkValidity()) { f.reportValidity(); return false; }
    }
    return true;
  };

  const handleNext = async () => {
    if (!validate()) return;

    // Step 0 → register patient
    if (step === 0) {
      setLoading(true);
      const { data, error } = await registerPatient(form);
      setLoading(false);
      if (error) {
        // Detect common RLS / permission failures
        const isRLS = error.message?.includes("row-level security") || error.code === "42501" || error.code === "PGRST301";
        const isNetErr = error.message?.includes("Failed to fetch") || error.message?.includes("NetworkError");
        let msg = error.message;
        if (isRLS) msg = "Database permission denied. Check RLS settings.";
        if (isNetErr) msg = "Cannot reach the database. Check connection.";
        addToast(msg, "error", 4000);
        return;
      }
      setPatientId(data.id);
      addToast(`Patient registered (ID: ${data.id.slice(0, 8)}…)`, "success", 2000);
    }

    // Step 3 → run AI Diagnosis
    if (step === 3 && !aiResult) {
      setLoading(true);
      const result = await runAIDiagnosis(form);
      setAiResult(result);
      setLoading(false);

      // Create encounter record
      const { data: enc } = await createEncounter(patientId, form, result);
      if (enc) setEncounterId(enc.id);

      // Upload any files selected in the Symptoms step.
      if (enc?.id && form.files?.length) {
        const up = await uploadEncounterFiles({
          patientId,
          encounterId: enc.id,
          files: form.files,
        });
        if (up.error) addToast("Upload failed: " + up.error.message, "error", 4000);
      }

      // Auto-create emergency alert for high severity
      if (result.severity === "High") {
        await createEmergencyAlert(patientId, form.name, form.department, "High", form.symptoms);
      }

      // Auto-create lab order for high severity
      if (result.severity === "High" && result.labTests?.length) {
        await createLabOrder(patientId, enc?.id, "AI Triage", result.labTests, "Urgent", "Auto-generated by AI");
      }
      return;
    }

    // Step 4 → save appointment
    if (step === 4) {
      setLoading(true);
      const { error: apptErr } = await createAppointment(patientId, encounterId, form);
      setLoading(false);
      if (apptErr) {
        addToast("Could not book appointment: " + apptErr.message, "error", 4000);
        return;
      }
      addToast("Appointment booked! Reception will confirm your slot.", "success", 2000);
      setTimeout(() => navigate("/"), 2000);
      return;
    }

    setStep((s) => Math.min(4, s + 1));
  };

  const progress = ((step + 1) / STEPS.length) * 100;

  return (
    <div className="stackMd">
      {/* Stepper */}
      <div className="stepHeader">
        <div className="stepHeaderRow">
          <span style={{ letterSpacing: "0.18em", textTransform: "uppercase" }}>Step {step + 1} of {STEPS.length}</span>
          <span>{STEPS[step].description}</span>
        </div>
        <div className="stepper" style={{ gridTemplateColumns: `repeat(${STEPS.length}, 1fr)` }}>
          {STEPS.map((s, i) => (
            <div key={s.label} className="stepItem">
              <div className={`stepIcon ${i === step ? "stepIconActive" : i < step ? "stepIconDone" : ""}`}>
                <s.Icon width={13} height={13} />
              </div>
              <span className={`stepLabel ${i === step ? "stepLabelActive" : ""}`}>{s.label}</span>
            </div>
          ))}
        </div>
        <Progress value={progress} style={{ marginTop: "0.5rem" }} />
      </div>

      {/* Panel card */}
      <div className="panelCard">
        <div className="panelHeader">
          <div className="panelTitleRow">
            <div className="panelIconBox"><RoleIcon width={20} height={20} style={{ color: accentColor }} /></div>
            <div>
              <p className="panelKicker">Patient journey</p>
              <h1 className="panelTitle">{STEPS[step].description}</h1>
            </div>
          </div>
        </div>
        <p className="panelSub">{step === 0 ? "Enter your details to register" : STEPS[step].description}</p>
      </div>



      {/* ── Step 0: Registration ── */}
      {step === 0 && (
        <div className="stackMd" data-step="0">
          <div className="formGrid2">
            <div>
              <label className="formLabel">Full Name *</label>
              <Input placeholder="Full name" value={form.name} onChange={e => upd({ name: e.target.value })} required minLength={2} />
            </div>
            <div>
              <label className="formLabel">Age *</label>
              <Input type="number" placeholder="Age" value={form.age} onChange={e => upd({ age: e.target.value })} required min={0} max={120} />
            </div>
          </div>
          <div className="formGrid2">
            <div>
              <label className="formLabel">Gender *</label>
              <select className="formSelect" value={form.gender} onChange={e => upd({ gender: e.target.value })} required>
                <option value="">Select gender</option>
                <option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option>
              </select>
            </div>
            <div>
              <label className="formLabel">Phone *</label>
              <Input type="tel" placeholder="10-digit phone" value={form.phone} onChange={e => upd({ phone: e.target.value })} required pattern="[0-9]{10}" title="Enter 10-digit phone" />
            </div>
          </div>
          <div>
            <label className="formLabel">Email *</label>
            <Input type="email" placeholder="Email address" value={form.email} onChange={e => upd({ email: e.target.value })} required />
          </div>
          <div>
            <label className="formLabel">Address *</label>
            <Input placeholder="Full address" value={form.address} onChange={e => upd({ address: e.target.value })} required />
          </div>
          <div>
            <label className="formLabel">Emergency Contact *</label>
            <Input type="tel" placeholder="Emergency contact number" value={form.emergencyContact} onChange={e => upd({ emergencyContact: e.target.value })} required pattern="[0-9]{10}" />
          </div>
        </div>
      )}

      {/* ── Step 1: Department ── */}
      {step === 1 && (
        <div className="stackMd" data-step="1">
          <p className="muted">Choose the department that best matches your health concern.</p>
          <div>
            <label className="formLabel">Department *</label>
            <select className="formSelect" value={form.department} onChange={e => upd({ department: e.target.value })} required>
              <option value="">Select department</option>
              {Object.keys(DOCTOR_MAP).map(d => <option key={d}>{d}</option>)}
            </select>
          </div>
          {form.department && (
            <div className="note noteStrong">
              <p className="formLabel" style={{ marginBottom: 8 }}>Available doctors in {form.department}</p>
              <ul className="simpleList">
                {(DOCTOR_MAP[form.department] || []).map(d => <li key={d}>• {d}</li>)}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* ── Step 2: Symptoms ── */}
      {step === 2 && (
        <div className="stackMd" data-step="2">
          <div>
            <label className="formLabel">Describe your symptoms *</label>
            <Textarea placeholder="Describe your symptoms in detail..." value={form.symptoms} onChange={e => upd({ symptoms: e.target.value })} required rows={4} />
          </div>
          <div className="formGrid2">
            <div>
              <label className="formLabel">Duration *</label>
              <Input placeholder="e.g. 3 days, 2 weeks" value={form.duration} onChange={e => upd({ duration: e.target.value })} required />
            </div>
            <div>
              <label className="formLabel">Severity (1–10): <strong>{form.severity}</strong></label>
              <input type="range" min={1} max={10} value={form.severity} onChange={e => upd({ severity: Number(e.target.value) })} className="range" />
            </div>
          </div>
          <div className="formGrid2">
            <div>
              <label className="formLabel">Past medical history (optional)</label>
              <Textarea placeholder="Diabetes, hypertension, surgeries..." value={form.history} onChange={e => upd({ history: e.target.value })} />
            </div>
            <div>
              <label className="formLabel">Allergies (optional)</label>
              <Textarea placeholder="Drug or food allergies..." value={form.allergies} onChange={e => upd({ allergies: e.target.value })} />
            </div>
          </div>
          <div>
            <label className="formLabel">Upload symptom images (optional)</label>
            <Input type="file" accept="image/*" multiple onChange={e => upd({ files: e.target.files ? Array.from(e.target.files) : [] })} className="fileInput" />
            {form.files.length > 0 && (
              <ul className="fileList">{form.files.map(f => <li key={f.name}>📎 {f.name}</li>)}</ul>
            )}
          </div>
        </div>
      )}

      {/* ── Step 3: AI Diagnosis ── */}
      {step === 3 && (
        <div className="stackMd">
          {loading && (
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", padding: "1.25rem", background: "hsl(var(--muted))", borderRadius: "0.75rem" }}>
              <span className="spinner" />
              <span style={{ fontSize: "0.9rem", color: "hsl(var(--muted-foreground))" }}>Running diagnosis on your symptoms…</span>
            </div>
          )}

          {!aiResult && !loading && (
            <div style={{ padding: "1.5rem", background: "hsl(var(--muted))", borderRadius: "0.75rem", textAlign: "center" }}>
              <FlaskConical width={28} height={28} style={{ color: "hsl(199 89% 52%)", margin: "0 auto 0.5rem" }} />
              <p style={{ fontSize: "0.9rem", color: "hsl(var(--muted-foreground))" }}>Hit <strong>Next</strong> to run the AI analysis on your symptoms.</p>
            </div>
          )}

          {aiResult && (
            <div className="stackMd">
              {/* Severity + Confidence header */}
              <div style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: "0.75rem",
              }}>
                {/* Severity Card */}
                <div style={{
                  padding: "1.1rem 1.25rem",
                  borderRadius: "0.875rem",
                  border: `2px solid ${aiResult.severity === "High" ? "hsl(0 80% 55%)" : aiResult.severity === "Moderate" ? "hsl(38 95% 50%)" : "hsl(140 60% 45%)"}`,
                  background: `${aiResult.severity === "High" ? "hsl(0 80% 55% / 0.08)" : aiResult.severity === "Moderate" ? "hsl(38 95% 50% / 0.08)" : "hsl(140 60% 45% / 0.08)"}`,
                }}>
                  <p style={{ fontSize: "0.7rem", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "hsl(var(--muted-foreground))", marginBottom: "0.35rem" }}>Severity</p>
                  <p style={{ fontSize: "1.4rem", fontWeight: 800, color: aiResult.severity === "High" ? "hsl(0 80% 60%)" : aiResult.severity === "Moderate" ? "hsl(38 95% 50%)" : "hsl(140 60% 48%)" }}>
                    {aiResult.severity === "High" ? "🔴" : aiResult.severity === "Moderate" ? "🟡" : "🟢"} {aiResult.severity}
                  </p>
                </div>

                {/* Confidence Card */}
                <div style={{ padding: "1.1rem 1.25rem", borderRadius: "0.875rem", border: "1px solid hsl(var(--border))", background: "hsl(var(--muted))" }}>
                  <p style={{ fontSize: "0.7rem", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "hsl(var(--muted-foreground))", marginBottom: "0.5rem" }}>AI Confidence</p>
                  <p style={{ fontSize: "1.4rem", fontWeight: 800, marginBottom: "0.4rem" }}>{Math.round(aiResult.confidence * 100)}%</p>
                  <div style={{ height: "4px", background: "hsl(var(--border))", borderRadius: "2px", overflow: "hidden" }}>
                    <div style={{ height: "100%", width: `${Math.round(aiResult.confidence * 100)}%`, background: "hsl(199 89% 52%)", borderRadius: "2px", transition: "width 0.6s ease" }} />
                  </div>
                </div>
              </div>

              {/* Recommendation */}
              <div style={{ padding: "1rem 1.2rem", borderRadius: "0.75rem", border: "1px solid hsl(var(--border))", background: "hsl(var(--card))" }}>
                <p style={{ fontSize: "0.7rem", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: "hsl(var(--muted-foreground))", marginBottom: "0.5rem" }}>Recommendation</p>
                <p style={{ fontSize: "0.9rem", lineHeight: 1.6 }}>{aiResult.recommendation}</p>
              </div>

              {/* Diagnosis summary */}
              {aiResult.diagnosisText && (
                <div style={{ padding: "1rem 1.2rem", borderRadius: "0.75rem", background: "hsl(var(--muted))", fontSize: "0.85rem", lineHeight: 1.7, whiteSpace: "pre-line", color: "hsl(var(--foreground))" }}>
                  {aiResult.diagnosisText}
                </div>
              )}

              {/* Lab Tests */}
              {aiResult.labTests?.length > 0 && (
                <div style={{ padding: "1rem 1.2rem", borderRadius: "0.75rem", border: "1px solid hsl(199 89% 52% / 0.35)", background: "hsl(199 89% 52% / 0.06)" }}>
                  <p style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "hsl(199 89% 52%)", marginBottom: "0.75rem" }}>🔬 Recommended Lab Tests</p>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: "0.4rem" }}>
                    {aiResult.labTests.map(t => (
                      <span key={t} style={{ padding: "0.25rem 0.7rem", borderRadius: "999px", background: "hsl(199 89% 52% / 0.15)", color: "hsl(199 89% 55%)", fontSize: "0.78rem", fontWeight: 600, border: "1px solid hsl(199 89% 52% / 0.3)" }}>
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Medications */}
              {aiResult.medications?.length > 0 && (
                <div style={{ padding: "1rem 1.2rem", borderRadius: "0.75rem", border: "1px solid hsl(var(--border))", background: "hsl(var(--card))" }}>
                  <p style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "hsl(var(--muted-foreground))", marginBottom: "0.75rem" }}>💊 Suggested Medications <span style={{ fontWeight: 400, textTransform: "none", letterSpacing: 0 }}>(consult doctor first)</span></p>
                  <ul style={{ margin: 0, padding: "0 0 0 1rem", display: "flex", flexDirection: "column", gap: "0.3rem" }}>
                    {aiResult.medications.map(m => <li key={m} style={{ fontSize: "0.87rem" }}>{m}</li>)}
                  </ul>
                </div>
              )}

              {/* Home remedies */}
              {aiResult.remedies?.length > 0 && (
                <div style={{ padding: "1rem 1.2rem", borderRadius: "0.75rem", border: "1px solid hsl(140 60% 45% / 0.35)", background: "hsl(140 60% 45% / 0.06)" }}>
                  <p style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "hsl(140 60% 45%)", marginBottom: "0.75rem" }}>🌿 Home Care Tips</p>
                  <ul style={{ margin: 0, padding: "0 0 0 1rem", display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                    {aiResult.remedies.map(r => <li key={r} style={{ fontSize: "0.87rem" }}>{r}</li>)}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* ── Step 4: Appointment ── */}
      {step === 4 && (
        <div className="stackMd" data-step="4">
          <div>
            <label className="formLabel">Doctor *</label>
            <select className="formSelect" value={form.doctor} onChange={e => upd({ doctor: e.target.value })} required>
              <option value="">Select doctor</option>
              {(DOCTOR_MAP[form.department] || ["Duty doctor on call"]).map(d => <option key={d}>{d}</option>)}
            </select>
          </div>
          <div className="formGrid2">
            <div>
              <label className="formLabel">Preferred date *</label>
              <Input type="date" value={form.appointmentDate} onChange={e => upd({ appointmentDate: e.target.value })} required />
            </div>
            <div>
              <label className="formLabel">Preferred time *</label>
              <Input type="time" value={form.appointmentTime} onChange={e => upd({ appointmentTime: e.target.value })} required />
            </div>
          </div>
          <div className="note noteStrong">
            <p className="formLabel" style={{ marginBottom: 8 }}>Appointment Summary</p>
            <div className="dataRow"><span className="dataKey">Patient</span><span>{form.name}</span></div>
            <div className="dataRow" style={{ marginTop: 6 }}><span className="dataKey">Department</span><span>{form.department}</span></div>
            <div className="dataRow" style={{ marginTop: 6 }}><span className="dataKey">Doctor</span><span>{form.doctor || "—"}</span></div>
            {aiResult && <div className="dataRow" style={{ marginTop: 6 }}><span className="dataKey">AI Severity</span><span className={`pill ${aiResult.severity === "High" ? "pillHigh" : aiResult.severity === "Moderate" ? "pillModerate" : "pillMild"}`}>{aiResult.severity}</span></div>}
          </div>
          <p className="muted" style={{ fontSize: 13 }}>Final confirmation will be shared by our reception team.</p>
        </div>
      )}

      {/* Footer */}
      <div className="wizardFooter">
        <Button type="button" variant="outline" className="wizardBtn" onClick={() => { setStep(s => Math.max(0, s - 1)); }} disabled={step === 0}>
          Back
        </Button>
        <Button type="button" className="wizardBtn" onClick={handleNext} disabled={loading}>
          {loading ? <><span className="spinner" /> Processing…</> : step === 4 ? "Confirm Booking" : <>Next <ArrowRight width={16} height={16} /></>}
        </Button>
      </div>
    </div>
  );
}
